config1 = {
    "root_dir": ".",
    "tag": "default",
    "debug": False,
    "gpt_temperature": 0.8,
    "prompt_folder": "vanilla_task_generation_prompt",
    "max_env_run_cnt": 3,
    "trials": 1,
    "output_folder": "output/output_stats/",
    "model_output_dir": "",
    "gpt_model": "gpt-4o",
    "llama_model_name": "",
    "use_vllm": False,
    "n_gpus": 1,
    "openai_key": "",
    "genai_key": "",
    "llama_key": "",
    "hf_token": "",
    "task_description_candidate_num": -1,
    "task_asset_candidate_num": -1,
    "task_code_candidate_num": 4,
    "prompt_data_path": "prompts/data/",
    "save_data": True,
    "save_memory": False,
    "load_memory": False,
    "use_template": False,
    "reflection_agreement_num": 2,
    "target_task_name": "",
    "target_task_description": "",
    "save_code_early": False,
    "load_task_num": -1,

    "data_dir": "$/data",
    "assets_root": "/Users/maxfest/vscode/thesis/ravens/environments/assets",
    "disp": True,
    "shared_memory": False,
    "task": "build-cube",
    "mode": "cap",
    "n": 1,
    "random": True,
    "save_data": False,
    "check": False,
    "check_using_VLM": False,
    "manual_eval": False,
    "dataset": {
        "type": "single",
        "images": True,
        "cache": True,
        "augment": {
            "theta_sigma": 60
        }
    },
    "record": {
        "save_video": False,
        "save_video_path": "${data_dir}/${task}-cap/videos/",
        "add_text": True,
        "add_task_text": True,
        "fps": 20,
        "video_height": 640,
        "video_width": 720
    }
}
